import { Resend } from 'resend';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
dotenv.config();

const resendApiKey = process.env.RESEND_API_KEY || '';
const resend = resendApiKey ? new Resend(resendApiKey) : null;

const smtpHost = process.env.SMTP_HOST || 'smtp.hostinger.com';
const smtpPort = Number(process.env.SMTP_PORT) || 465;
const smtpSecure = process.env.SMTP_SECURE === 'true' || smtpPort === 465;
const smtpUser = process.env.SMTP_USER || 'noreply@pgmart.in';
const smtpPass = process.env.SMTP_PASS || '';
const smtpFromName = process.env.SMTP_FROM_NAME || 'PGmart';
const adminEmail = process.env.ADMIN_EMAIL || 'admin@pgmart.in';

// Create Nodemailer Transporter as fallback
export const transporter = nodemailer.createTransport({
  host: smtpHost,
  port: smtpPort,
  secure: smtpSecure,
  auth: smtpUser ? {
    user: smtpUser,
    pass: smtpPass
  } : undefined,
  tls: {
    rejectUnauthorized: false
  }
});

/**
 * Send branded 6-digit OTP Verification Email to recipient
 * @param toEmail Recipient email address
 * @param otpCode 6-digit OTP code string
 */
export async function sendOtpEmail(toEmail: string, otpCode: string): Promise<boolean> {
  const fromHeader = `"${smtpFromName}" <${smtpUser}>`;
  
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; padding: 28px; max-width: 500px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 16px; background-color: #ffffff;">
      <div style="text-align: center; margin-bottom: 24px;">
        <span style="background-color: #C0654B; color: #ffffff; font-weight: bold; font-size: 22px; padding: 12px 18px; border-radius: 50%; display: inline-block;">PG</span>
        <h2 style="color: #2B2620; margin-top: 14px; font-size: 22px; font-weight: 700;">PGmart Verification Code</h2>
      </div>
      <p style="color: #4A4A4A; font-size: 14px; line-height: 1.5; text-align: center;">
        Thank you for joining <strong>PGmart</strong>. Use the 6-digit security code below to complete your account registration:
      </p>
      <div style="font-size: 34px; font-weight: 800; letter-spacing: 8px; color: #C0654B; text-align: center; margin: 28px 0; padding: 18px; background-color: #FAF7F5; border-radius: 12px; border: 2px dashed #C0654B;">
        ${otpCode}
      </div>
      <p style="color: #666666; font-size: 12px; text-align: center; line-height: 1.4;">
        ⏱️ This code is valid for <strong>10 minutes</strong>. Do not share this OTP with anyone for your account security.
      </p>
      <hr style="border: none; border-top: 1px solid #eeeeee; margin: 24px 0;" />
      <p style="color: #999999; font-size: 11px; text-align: center;">
        If you did not request this email, please ignore it or contact <a href="mailto:${adminEmail}" style="color: #C0654B;">${adminEmail}</a>.
      </p>
    </div>
  `;

  // 1. Primary: Use Resend API if API Key is configured
  if (resend) {
    try {
      const data = await resend.emails.send({
        from: 'PGmart <onboarding@resend.dev>',
        to: [toEmail],
        subject: `Your PGmart Verification Code: ${otpCode}`,
        html: htmlContent,
      });
      console.log(`[Resend Mailer] OTP email successfully dispatched to ${toEmail}:`, data);
      return true;
    } catch (resendErr: any) {
      console.warn(`[Resend Error] Falling back to Nodemailer SMTP:`, resendErr?.message || resendErr);
    }
  }

  // 2. Fallback: Use Nodemailer SMTP
  try {
    const info = await transporter.sendMail({
      from: fromHeader,
      to: toEmail,
      subject: `Your PGmart Verification Code: ${otpCode}`,
      html: htmlContent
    });
    console.log(`[Mailer] OTP email successfully sent to ${toEmail} (Message ID: ${info.messageId})`);
    return true;
  } catch (err: any) {
    console.error(`[Mailer Error] Failed to send OTP email to ${toEmail}:`, err?.message || err);
    return false;
  }
}

/**
 * Send administrative alert email to ADMIN_EMAIL (admin@pgmart.in)
 */
export async function sendAdminAlert(subject: string, message: string): Promise<boolean> {
  const fromHeader = `"${smtpFromName} Security Alert" <${smtpUser}>`;

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; padding: 24px; max-width: 550px; border: 1px solid #ffcccc; border-radius: 12px; background-color: #fff8f8;">
      <h3 style="color: #d9534f; margin-top: 0;">⚠️ Security Alert Notification</h3>
      <p style="color: #333333; font-size: 14px; font-weight: bold;">Subject: ${subject}</p>
      <div style="background-color: #ffffff; padding: 16px; border-radius: 8px; border: 1px solid #e0e0e0; font-size: 13px; color: #444444; white-space: pre-wrap;">
        ${message}
      </div>
      <p style="color: #888888; font-size: 11px; margin-top: 16px;">
        Timestamp: ${new Date().toISOString()}<br />
        Automated alert generated by PGmart Security Monitor.
      </p>
    </div>
  `;

  if (resend) {
    try {
      await resend.emails.send({
        from: 'PGmart Security <onboarding@resend.dev>',
        to: [adminEmail],
        subject: `[ADMIN ALERT] ${subject}`,
        html: htmlContent,
      });
      console.log(`[Resend Mailer] Admin alert sent to ${adminEmail}`);
      return true;
    } catch (e) {}
  }

  try {
    const info = await transporter.sendMail({
      from: fromHeader,
      to: adminEmail,
      subject: `[ADMIN ALERT] ${subject}`,
      html: htmlContent
    });
    console.log(`[Mailer] Admin alert sent to ${adminEmail} (Message ID: ${info.messageId})`);
    return true;
  } catch (err: any) {
    console.error(`[Mailer Error] Failed to send admin alert to ${adminEmail}:`, err?.message || err);
    return false;
  }
}
